nb_of_topics: 3
topic_1:
  name: imu
  topic_name: /topic1
  min_freq: 80

topic_2:
  name: depth_camera
  topic_name: /topic2
  min_freq: 3

topic_3:
  name: gps
  topic_name: /topic3
  min_freq: 0.5